services:
  tgupbot:
    build: .
    container_name: tgupbot
    env_file:
      - .env
    volumes:
      - ./accounts.json:/app/accounts.json:ro
      - ./data:/app/data
    restart: unless-stopped
